### ISSUE TITLE
[support] Help to config.

### ISSUE THREAD

**Issue by nguyenvanduocit** [Inlife/nexrender#11]
I have some question about config.
Here is my config:
```
var api = require('nexrender').api;

// Configure api connection
api.config({
    host: "localhost",
    port: 3000
});

// Define project properties
var assets = [{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    'name': '001.png'
},{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    'name': '002.png'
},{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    'name': '003.png'
}];

// Create project
api.create({
    template: 'pokemon.aep',
    composition: 'main',
    assets: assets
}).then((project) => {

    console.log('project saved');

    project.on('rendering', function(err, project) {
        console.log('project rendering started');
    });

    project.on('finished', function(err, project) {
        console.log('project rendering finished')
    });

    project.on('failure', function(err, project) {
        console.log('project rendering error')
    });
});
```

But after run code. AE show a dialog to select composition. after that, the rended video the same with the template. btw, the template is aet not aepx. I don't know why.
please help. Or give me an sample.
Thanks

**Comment by Inlife** [comment]
Hey!

First of all, you **never ever need to open Adobe After Effects** to actually render video via nexrender. It uses command line binary application built-in After Effects. Which you need to set path to.

I assume, your current render task for now is pretty simple, so i'd like to show you how you can achieve results fast:

### No API-Server neded

* Goto your directory, where you'll be running nexrender:
```sh
$ cd ~/....../MyMegaProjects/PokemonVideo/
```

* Make sure there is an `templates/` folder, and your `pokemon.aep` is located inside

* Create script called for example `render_pokemon.js` at `PokemonVideo/` with that content:

```js
var Project   = require('nexrender/api/models/project');
var renderer  = require('nexrender/renderer');

var assets = [{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    'name': '001.png'
},{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    'name': '002.png'
},{
    'type': 'image',
    'src': 'http://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    'name': '003.png'
}];

var project = new Project({
    'template': 'pokemon.aep',
    'composition': 'main',
    'assets': assets,
    'settings': {
        outputModule: 'h264' // make sure 
       // you've set up your After Effects output module correctly
    }
});

// start rendering
// NOTE: i inserted path to my aerender binary
// if you are on windows, your path might look like:
// 'C:\\Program Files\Adobe\After Effects CC 2015\aerender.exe'
var rendered = renderer.render('/Applications/Adobe After Effects CC 2015.3/aerender', project);

rendered.then(function() {
    // successfully rendered
    console.log('yay!');
});
```

* Install nexrender locally (inside `PokemonVideo/` folder):
```sh
npm install nexrender # the latest version was 0.4.10 on the time of this post
```
* Run everyting:
```sh
node render_pokemon.js
```

That should be working fine :)

**Comment by nguyenvanduocit** [comment]
I use aerender version 13.8.1x38 then got error message `Error message: aerender version 13.8.1x38`. and aep file `temp` folder still the same with the template, no image changed.
I will try with othe ae version

**Comment by Inlife** [comment]
Wait, seems to me it isn't actual error message.
Could you please send all output ?

**Comment by Inlife** [comment]
additional info for using nexrender can be found there:
https://github.com/Inlife/nexrender-boilerplate

**Comment by KhejjouM** [comment]
Hello @inlife , 

I am trying to use your repo but I want to put a video as a background, is it possible ?

**Comment by inlife** [comment]
i think it is, havent tested myself, but in theory should work

**Comment by inlife** [comment]
well thats just a usual assets, i was just adding expressions to control some of the parameters
you can checkout the boilerplate project for an example: https://github.com/inlife/nexrender-boilerplate
